### ISSUE TITLE
Segmentation Faults

### ISSUE THREAD

**Issue by ralanharris** [jkimlab/DESCHRAMBLER#1]
Make runs through without errors, but I get segmentation faults from the following programs:

createGenomeFile
makeConservedSegments
orthoBlocksToOrders
outgroupSegsToOrders
deschrambler

The seg faults occur even if I just run the program without any parameters. Other programs give usage information if I run them without any parameters. 

I am running on a x86_64 system with CentOS 6.6. I have tried gcc versions 4.9.4 and 6.3.0. Do you have any idea what I need to change to correctly compile on this system? Alternatively, could you tell me the OS and gcc version that you used so I can try to replicate that?

Thanks,

Alan

**Comment by jkimlab** [comment]
Sorry for the problem.
We tested our code on a CentOS 6.5 and 6.9 with gcc 4.8.5. If you do not provide parameters, that may the reason of causing the segmentation faults.
Please try again. Thanks.

**Comment by xuyuannnn** [comment]
I meet the same preblem:
It tells me that:
/bin/sh: line 1: 30026 Segmentation fault      /data/home/xuyuan/biosoft/D/DESCHRAMBLER/code/makeBlocks/createGenomeFile config.file Conserved.Segments > Genomes.Order
make: *** [Makefile:57: Genomes.Order] Error 139

the same preblem to following scripts:
createGenomeFile
makeConservedSegments
orthoBlocksToOrders
outgroupSegsToOrders

so , Is there a compilation error? What can I do about it?
my gcc version is 4.8.5

thanks
