### ISSUE TITLE
test example failed

### ISSUE THREAD

**Issue by yuzhenpeng** [jkimlab/DESCHRAMBLER#10]
Hi,

When I run the example, I got the warnings. Could you help me.

`$perl ../DESCHRAMBLER.pl ./params.txt

## Constructing syntenic fragments ##
Error - Could not open net dir /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/chainNet/spc1/spc2/net/spc1/spc2/net
- processing spc2.raw.segs
- processing spc3.raw.segs
- getting segments from spc2.processed.segs
- getting segments from spc3.processed.segs
- adding descendent spc2
  in ref chr3
  in ref chr2 ..
  in ref chr1 ......
- adding outgroup spc3
  in ref chr3 .Cannot open /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/chainNet/spc1/spc2/chain/spc1/spc3/chain/chr3.chain.
make: *** [Makefile:23: Building.Blocks] Error 1
Error - Could not open net dir /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/chainNet/spc1/spc2/net/spc1/spc2/net
- processing spc2.raw.segs
- getting segments from spc2.processed.segs
- adding descendent spc2
  in ref chr3
  in ref chr2 ..
  in ref chr1 ......
Error - Could not open net dir /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/chainNet/spc1/spc2/net/spc1/spc3/net
- processing spc3.raw.segs
- getting segments from spc3.processed.segs
- adding descendent spc3
  in ref chr3 ...
  in ref chr2 .....
  in ref chr1 .....
TREE ((spc1:0.02,spc2:0.02)@:0.02,spc3:0.02);

UNIVERSAL does not export anything at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
Compilation failed in require at /usr/share/perl5/base.pm line 138.
        ...propagated at /usr/share/perl5/base.pm line 160.
BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/Tree.pm line 111.
Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90.
BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90.
Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/estparJC.pl line 7.
BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/estparJC.pl line 7.
Estimate JC parameter:
inferAdjProb - inferring the posterior probability of block adjacency
  usage: inferAdjProb refspc parameter-alpha tree-file genome-file

readline() on closed filehandle F at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/refine_adjprob.pl line 11.
Minimum weight = 0.0001
Conservation score file = /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/APCFs.300K/SFs/block_consscores.txt
UNIVERSAL does not export anything at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
Compilation failed in require at /usr/share/perl5/base.pm line 138.
        ...propagated at /usr/share/perl5/base.pm line 160.
BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/Tree.pm line 111.
Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90.
BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90.
Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/split_weak_joins.pl line 7.
BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/split_weak_joins.pl line 7.
UNIVERSAL does not export anything at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
Compilation failed in require at /usr/share/perl5/base.pm line 138.
        ...propagated at /usr/share/perl5/base.pm line 160.
BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/Tree.pm line 111.
Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90.
BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90.
Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/join_splits.pl line 7.
BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/join_splits.pl line 7.
- Totally 0 APCFs
sh: line 1: 497883 Segmentation fault      (core dumped) /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../code/makeBlocks/createCarFile /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/APCFs.300K/SFs/config.file /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/APCFs.300K/Ancestor.APCF /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/APCFs.300K/SFs/Conserved.Segments > /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/APCFs.300K/APCFs`

Thank you.

**Comment by Morriyaty** [comment]
Have you fixed it? I met a similar error and my log file listed followed.
[log.txt](https://github.com/jkimlab/DESCHRAMBLER/files/8403837/log.txt)
.

**Comment by jkimlab** [comment]
> Hi,
> 
> When I run the example, I got the warnings. Could you help me.
> 
> `$perl ../DESCHRAMBLER.pl ./params.txt
> 
> ## Constructing syntenic fragments
> Error - Could not open net dir /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/chainNet/spc1/spc2/net/spc1/spc2/net
> 
> * processing spc2.raw.segs
> * processing spc3.raw.segs
> * getting segments from spc2.processed.segs
> * getting segments from spc3.processed.segs
> * adding descendent spc2
>   in ref chr3
>   in ref chr2 ..
>   in ref chr1 ......
> * adding outgroup spc3
>   in ref chr3 .Cannot open /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/chainNet/spc1/spc2/chain/spc1/spc3/chain/chr3.chain.
>   make: *** [Makefile:23: Building.Blocks] Error 1
>   Error - Could not open net dir /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/chainNet/spc1/spc2/net/spc1/spc2/net
> * processing spc2.raw.segs
> * getting segments from spc2.processed.segs
> * adding descendent spc2
>   in ref chr3
>   in ref chr2 ..
>   in ref chr1 ......
>   Error - Could not open net dir /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/chainNet/spc1/spc2/net/spc1/spc3/net
> * processing spc3.raw.segs
> * getting segments from spc3.processed.segs
> * adding descendent spc3
>   in ref chr3 ...
>   in ref chr2 .....
>   in ref chr1 .....
>   TREE ((spc1:0.02,spc2:0.02)@:0.02,spc3:0.02);
> 
> UNIVERSAL does not export anything at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94. Compilation failed in require at /usr/share/perl5/base.pm line 138. ...propagated at /usr/share/perl5/base.pm line 160. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/Tree.pm line 111. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/estparJC.pl line 7. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/estparJC.pl line 7. Estimate JC parameter: inferAdjProb - inferring the posterior probability of block adjacency usage: inferAdjProb refspc parameter-alpha tree-file genome-file
> 
> readline() on closed filehandle F at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/refine_adjprob.pl line 11. Minimum weight = 0.0001 Conservation score file = /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/APCFs.300K/SFs/block_consscores.txt UNIVERSAL does not export anything at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94. Compilation failed in require at /usr/share/perl5/base.pm line 138. ...propagated at /usr/share/perl5/base.pm line 160. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/Tree.pm line 111. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/split_weak_joins.pl line 7. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/split_weak_joins.pl line 7. UNIVERSAL does not export anything at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94. Compilation failed in require at /usr/share/perl5/base.pm line 138. ...propagated at /usr/share/perl5/base.pm line 160. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/Tree.pm line 111. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/join_splits.pl line 7. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/join_splits.pl line 7.
> 
> * Totally 0 APCFs
>   sh: line 1: 497883 Segmentation fault      (core dumped) /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../code/makeBlocks/createCarFile /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/APCFs.300K/SFs/config.file /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/APCFs.300K/Ancestor.APCF /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/APCFs.300K/SFs/Conserved.Segments > /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/APCFs.300K/APCFs`
> 
> Thank you.



> Hi,
> 
> When I run the example, I got the warnings. Could you help me.
> 
> `$perl ../DESCHRAMBLER.pl ./params.txt
> 
> ## Constructing syntenic fragments
> Error - Could not open net dir /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/chainNet/spc1/spc2/net/spc1/spc2/net
> 
> * processing spc2.raw.segs
> * processing spc3.raw.segs
> * getting segments from spc2.processed.segs
> * getting segments from spc3.processed.segs
> * adding descendent spc2
>   in ref chr3
>   in ref chr2 ..
>   in ref chr1 ......
> * adding outgroup spc3
>   in ref chr3 .Cannot open /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/chainNet/spc1/spc2/chain/spc1/spc3/chain/chr3.chain.
>   make: *** [Makefile:23: Building.Blocks] Error 1
>   Error - Could not open net dir /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/chainNet/spc1/spc2/net/spc1/spc2/net
> * processing spc2.raw.segs
> * getting segments from spc2.processed.segs
> * adding descendent spc2
>   in ref chr3
>   in ref chr2 ..
>   in ref chr1 ......
>   Error - Could not open net dir /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/chainNet/spc1/spc2/net/spc1/spc3/net
> * processing spc3.raw.segs
> * getting segments from spc3.processed.segs
> * adding descendent spc3
>   in ref chr3 ...
>   in ref chr2 .....
>   in ref chr1 .....
>   TREE ((spc1:0.02,spc2:0.02)@:0.02,spc3:0.02);
> 
> UNIVERSAL does not export anything at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94. Compilation failed in require at /usr/share/perl5/base.pm line 138. ...propagated at /usr/share/perl5/base.pm line 160. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/Tree.pm line 111. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/estparJC.pl line 7. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/estparJC.pl line 7. Estimate JC parameter: inferAdjProb - inferring the posterior probability of block adjacency usage: inferAdjProb refspc parameter-alpha tree-file genome-file
> 
> readline() on closed filehandle F at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/refine_adjprob.pl line 11. Minimum weight = 0.0001 Conservation score file = /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/APCFs.300K/SFs/block_consscores.txt UNIVERSAL does not export anything at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94. Compilation failed in require at /usr/share/perl5/base.pm line 138. ...propagated at /usr/share/perl5/base.pm line 160. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/Tree.pm line 111. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/split_weak_joins.pl line 7. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/split_weak_joins.pl line 7. UNIVERSAL does not export anything at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94. Compilation failed in require at /usr/share/perl5/base.pm line 138. ...propagated at /usr/share/perl5/base.pm line 160. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/Tree/Tree.pm line 111. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90. Compilation failed in require at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/join_splits.pl line 7. BEGIN failed--compilation aborted at /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/join_splits.pl line 7.
> 
> * Totally 0 APCFs
>   sh: line 1: 497883 Segmentation fault      (core dumped) /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/script/../code/makeBlocks/createCarFile /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/APCFs.300K/SFs/config.file /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/APCFs.300K/Ancestor.APCF /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/APCFs.300K/SFs/Conserved.Segments > /root/data1/yuzhenpeng2021/biosoft/DESCHRAMBLER/examples/APCFs.300K/APCFs`
> 
> Thank you.

It looks like the configuration for the chain/net directory might not be done correctly.

Can you show me the inside of the config.SFs file?

Thanks.

**Comment by jkimlab** [comment]
> Have you fixed it? I met a similar error and my log file listed followed. [log.txt](https://github.com/jkimlab/DESCHRAMBLER/files/8403837/log.txt) .

It may be related with the version of Perl. 

Can you try using Perl <= v5.16?

Thanks.

**Comment by Morriyaty** [comment]
@jkimlab
When I used the script with perl v5.16.3, I get the such log.
How can I fixed it？
[log.txt](https://github.com/jkimlab/DESCHRAMBLER/files/8406417/log.txt)

**Comment by jkimlab** [comment]
> @jkimlab When I used the script with perl v5.16.3, I get the such log. How can I fixed it？ [log.txt](https://github.com/jkimlab/DESCHRAMBLER/files/8406417/log.txt)

It looks like the "inferAdjProb" program was not properly compiled. Did you see any error messages when you first compiled the program?

**Comment by Morriyaty** [comment]
This is my log file when I compiled the program again.
[make.log](https://github.com/jkimlab/DESCHRAMBLER/files/8422794/make.log)
 Could you put the compiled program into a singularity container? haha : )

**Comment by jkimlab** [comment]
> This is my log file when I compiled the program again. [make.log](https://github.com/jkimlab/DESCHRAMBLER/files/8422794/make.log) Could you put the compiled program into a singularity container? haha : )

It may not be that easy. 
What OS (and version) are you using? If we don't have a machine with the same OS, it may not be possible to do that.

**Comment by Morriyaty** [comment]
Is there anything wrong with my make.log file when I compiled the program? 
I use linux with Centos.

**Comment by jkimlab** [comment]
Which version?

**Comment by Morriyaty** [comment]
Centos 8.5

**Comment by jkimlab** [comment]
I can’t make a program including the library because I don’t have a machine with Centos 8.5.

Alternatively, you can try to install the missing library in your machine. 

Try to install the GLIBC 2.28 by downloading the file from the following website. If you are not an administrator of the machine, ask the admin. do to that. 
https://centos.pkgs.org/8/centos-baseos-x86_64/glibc-2.28-164.el8.x86_64.rpm.html <https://centos.pkgs.org/8/centos-baseos-x86_64/glibc-2.28-164.el8.x86_64.rpm.html>

After that, recompile (type make clean; make) and run again. I hope this helps you.
