### ISSUE TITLE
test example file failed

### ISSUE THREAD

**Issue by kuangzhuoran** [jkimlab/DESCHRAMBLER#11]
Hi, Error while running data from example
Linux: Centos 8.5    
perl v5.32.1

herr is my log
[log.txt](https://github.com/jkimlab/DESCHRAMBLER/files/9431788/log.txt)

Or I print it out:
## Constructing syntenic fragments ##
- reading /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/chainNet/spc1/spc2/net/chr3.net
- reading /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/chainNet/spc1/spc2/net/chr1.net
- reading /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/chainNet/spc1/spc2/net/chr2.net
- reading /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/chainNet/spc1/spc3/net/chr3.net
- reading /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/chainNet/spc1/spc3/net/chr1.net
- reading /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/chainNet/spc1/spc3/net/chr2.net
- processing spc2.raw.segs
- processing spc3.raw.segs
- getting segments from spc2.processed.segs
- getting segments from spc3.processed.segs
- adding descendent spc2
  in ref chr3 
  in ref chr1 ......
  in ref chr2 ..
- adding outgroup spc3
  in ref chr3 ...
  in ref chr1 .....
  in ref chr2 .....
/bin/sh: line 1: 4090473 Segmentation fault      (core dumped) /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/code/makeBlocks/createGenomeFile config.file Conserved.Segments > Genomes.Order
make: *** [Makefile:57: Genomes.Order] Error 139
- reading /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/chainNet/spc1/spc2/net/chr3.net
- reading /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/chainNet/spc1/spc2/net/chr1.net
- reading /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/chainNet/spc1/spc2/net/chr2.net
- processing spc2.raw.segs
- getting segments from spc2.processed.segs
- adding descendent spc2
  in ref chr3 
  in ref chr1 ......
  in ref chr2 ..
- reading /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/chainNet/spc1/spc3/net/chr3.net
- reading /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/chainNet/spc1/spc3/net/chr1.net
- reading /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/chainNet/spc1/spc3/net/chr2.net
- processing spc3.raw.segs
- getting segments from spc3.processed.segs
- adding descendent spc3
  in ref chr3 ...
  in ref chr1 .....
  in ref chr2 .....
TREE ((spc1:0.02,spc2:0.02)@:0.02,spc3:0.02);

UNIVERSAL does not export anything at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
BEGIN failed--compilation aborted at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
Compilation failed in require at /usr/share/perl5/base.pm line 138.
	...propagated at /usr/share/perl5/base.pm line 160.
BEGIN failed--compilation aborted at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/Tree/Tree.pm line 111.
Compilation failed in require at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
BEGIN failed--compilation aborted at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
Compilation failed in require at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90.
BEGIN failed--compilation aborted at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90.
Compilation failed in require at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/estparJC.pl line 7.
BEGIN failed--compilation aborted at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/estparJC.pl line 7.
Estimate JC parameter: 
inferAdjProb - inferring the posterior probability of block adjacency
  usage: inferAdjProb refspc parameter-alpha tree-file genome-file

readline() on closed filehandle F at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/refine_adjprob.pl line 11.
Minimum weight = 0.0001
Conservation score file = /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/APCFs.300K/SFs/block_consscores.txt
UNIVERSAL does not export anything at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
BEGIN failed--compilation aborted at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
Compilation failed in require at /usr/share/perl5/base.pm line 138.
	...propagated at /usr/share/perl5/base.pm line 160.
BEGIN failed--compilation aborted at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/Tree/Tree.pm line 111.
Compilation failed in require at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
BEGIN failed--compilation aborted at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
Compilation failed in require at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90.
BEGIN failed--compilation aborted at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90.
Compilation failed in require at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/split_weak_joins.pl line 7.
BEGIN failed--compilation aborted at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/split_weak_joins.pl line 7.
UNIVERSAL does not export anything at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
BEGIN failed--compilation aborted at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
Compilation failed in require at /usr/share/perl5/base.pm line 138.
	...propagated at /usr/share/perl5/base.pm line 160.
BEGIN failed--compilation aborted at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/Tree/Tree.pm line 111.
Compilation failed in require at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
BEGIN failed--compilation aborted at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
Compilation failed in require at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90.
BEGIN failed--compilation aborted at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../lib/perl/Bio/TreeIO.pm line 90.
Compilation failed in require at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/join_splits.pl line 7.
BEGIN failed--compilation aborted at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/join_splits.pl line 7.
- Totally 0 APCFs
sh: line 1: 4090584 Segmentation fault      (core dumped) /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../code/makeBlocks/createCarFile /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/APCFs.300K/SFs/config.file /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/APCFs.300K/Ancestor.APCF /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/APCFs.300K/SFs/Conserved.Segments > /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/examples/APCFs.300K/APCFs

**Comment by jkimlab** [comment]
Very sorry for my late response.

I think it is because the BioPerl library in the \<path to DESCHRAMBLER\>/lib/perl/ is not compatible with a newer version of Perl.

I attached a new version. [Bio.tar.gz](https://github.com/jkimlab/DESCHRAMBLER/files/10527319/Bio.tar.gz)

Please completely replace the "Bio" directory in  \<path to DESCHRAMBLER\>/lib/perl/ by the attached one after uncompressing and untarring it. 

After that, you can rerun DESCHRAMBLER. Please don't forget to delete the previously created output directory. 

Thanks.

**Comment by kuangzhuoran** [comment]
Thanks a lot, It works!
