### ISSUE TITLE
Does not export anything at <DESCHRAMBLER-path>/TreeFunctionsI.pm line 94.

### ISSUE THREAD

**Issue by goblin290272908** [jkimlab/DESCHRAMBLER#12]
Hi,
Thank you for providing such an excellent tool.
But, when I run the example, I got the Err . Could you help me?

Linux: ubuntu 20.04
perl: v5.26.2 and 5.30.0
GLIBC: 2.31

I print it out:

## Constructing syntenic fragments ##
- reading /home/manager/bioapps/DESCHRAMBLER-master/examples/chainNet/spc1/spc2/net/chr1.net
- reading /home/manager/bioapps/DESCHRAMBLER-master/examples/chainNet/spc1/spc2/net/chr3.net
- reading /home/manager/bioapps/DESCHRAMBLER-master/examples/chainNet/spc1/spc2/net/chr2.net
- reading /home/manager/bioapps/DESCHRAMBLER-master/examples/chainNet/spc1/spc3/net/chr1.net
- reading /home/manager/bioapps/DESCHRAMBLER-master/examples/chainNet/spc1/spc3/net/chr3.net
- reading /home/manager/bioapps/DESCHRAMBLER-master/examples/chainNet/spc1/spc3/net/chr2.net
- processing spc2.raw.segs
- processing spc3.raw.segs
- getting segments from spc2.processed.segs
- getting segments from spc3.processed.segs
- adding descendent spc2
  in ref chr1 ......
  in ref chr3 
  in ref chr2 ..
- adding outgroup spc3
  in ref chr1 .....
  in ref chr3 ...
  in ref chr2 .....
Segmentation fault (core dumped)
make: *** [Makefile:57: Genomes.Order] Error 139
- reading /home/manager/bioapps/DESCHRAMBLER-master/examples/chainNet/spc1/spc2/net/chr1.net
- reading /home/manager/bioapps/DESCHRAMBLER-master/examples/chainNet/spc1/spc2/net/chr3.net
- reading /home/manager/bioapps/DESCHRAMBLER-master/examples/chainNet/spc1/spc2/net/chr2.net
- processing spc2.raw.segs
- getting segments from spc2.processed.segs
- adding descendent spc2
  in ref chr1 ......
  in ref chr3 
  in ref chr2 ..
- reading /home/manager/bioapps/DESCHRAMBLER-master/examples/chainNet/spc1/spc3/net/chr1.net
- reading /home/manager/bioapps/DESCHRAMBLER-master/examples/chainNet/spc1/spc3/net/chr3.net
- reading /home/manager/bioapps/DESCHRAMBLER-master/examples/chainNet/spc1/spc3/net/chr2.net
- processing spc3.raw.segs
- getting segments from spc3.processed.segs
- adding descendent spc3
  in ref chr1 .....
  in ref chr3 ...
  in ref chr2 .....
TREE ((spc1:0.02,spc2:0.02)@:0.02,spc3:0.02);

UNIVERSAL does not export anything at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
BEGIN failed--compilation aborted at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
Compilation failed in require at /usr/share/perl/5.30/base.pm line 137.
	...propagated at /usr/share/perl/5.30/base.pm line 159.
BEGIN failed--compilation aborted at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/Tree/Tree.pm line 111.
Compilation failed in require at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
BEGIN failed--compilation aborted at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
Compilation failed in require at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/TreeIO.pm line 90.
BEGIN failed--compilation aborted at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/TreeIO.pm line 90.
Compilation failed in require at /home/manager/bioapps/DESCHRAMBLER-master/script/estparJC.pl line 7.
BEGIN failed--compilation aborted at /home/manager/bioapps/DESCHRAMBLER-master/script/estparJC.pl line 7.
Estimate JC parameter: 
inferAdjProb - inferring the posterior probability of block adjacency
  usage: inferAdjProb refspc parameter-alpha tree-file genome-file

readline() on closed filehandle F at /home/manager/bioapps/DESCHRAMBLER-master/script/refine_adjprob.pl line 11.
Minimum weight = 0.0001
Conservation score file = /home/manager/bioapps/DESCHRAMBLER-master/examples/APCFs.300K/SFs/block_consscores.txt
UNIVERSAL does not export anything at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
BEGIN failed--compilation aborted at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
Compilation failed in require at /usr/share/perl/5.30/base.pm line 137.
	...propagated at /usr/share/perl/5.30/base.pm line 159.
BEGIN failed--compilation aborted at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/Tree/Tree.pm line 111.
Compilation failed in require at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
BEGIN failed--compilation aborted at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
Compilation failed in require at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/TreeIO.pm line 90.
BEGIN failed--compilation aborted at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/TreeIO.pm line 90.
Compilation failed in require at /home/manager/bioapps/DESCHRAMBLER-master/script/split_weak_joins.pl line 7.
BEGIN failed--compilation aborted at /home/manager/bioapps/DESCHRAMBLER-master/script/split_weak_joins.pl line 7.
UNIVERSAL does not export anything at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
BEGIN failed--compilation aborted at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/Tree/TreeFunctionsI.pm line 94.
Compilation failed in require at /usr/share/perl/5.30/base.pm line 137.
	...propagated at /usr/share/perl/5.30/base.pm line 159.
BEGIN failed--compilation aborted at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/Tree/Tree.pm line 111.
Compilation failed in require at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
BEGIN failed--compilation aborted at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/TreeIO/TreeEventBuilder.pm line 77.
Compilation failed in require at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/TreeIO.pm line 90.
BEGIN failed--compilation aborted at /home/manager/bioapps/DESCHRAMBLER-master/script/../lib/perl/Bio/TreeIO.pm line 90.
Compilation failed in require at /home/manager/bioapps/DESCHRAMBLER-master/script/join_splits.pl line 7.
BEGIN failed--compilation aborted at /home/manager/bioapps/DESCHRAMBLER-master/script/join_splits.pl line 7.
- Totally 0 APCFs
Segmentation fault (core dumped)

thankyou!!!!!!!!!

**Comment by jkimlab** [comment]
I think it is because the BioPerl library in the \<path to DESCHRAMBLER\>/lib/perl/ is not compatible with a newer version of Perl.

I attached a new version. 
[Bio.tar.gz](https://github.com/jkimlab/DESCHRAMBLER/files/10527328/Bio.tar.gz)

Please completely replace the "Bio" directory in  \<path to DESCHRAMBLER\>/lib/perl/ by the attached one after uncompressing and untarring it. 

After that, you can rerun DESCHRAMBLER. Please don't forget to delete the previously created output directory. 

Thanks.

**Comment by goblin290272908** [comment]
Thank you for your prompt response. My perllib path is /home/manager/perl5/lib/perl5/Bio, and i replace it with your DIR.
i find my perllib use command “$ perldoc -l Bio::Seq”。
However, it still prompts the previous error.

**Comment by jkimlab** [comment]
Sorry. My previous response was not entered correctly. 

DESCRAMBLER  is hard-coded to use the BioPerl library in the "lib/perl/" subdirectory in the install directory of DESCRAMBLER. Therefore, you have to replace the "Bio" subdirectory there, not in /home/manager/perl5/lib/perl5/.

**Comment by goblin290272908** [comment]
Thank you very much!!!!!!! 
all done !!!! 
Ammmmazing！
