### ISSUE TITLE
in ref chr7 wrong ref position: 49 spc1 chr7 4511181 spc3 chr5 + make: *** [Makefile:23: Building.Blocks] Error 1

### ISSUE THREAD

**Issue by Bilinhu** [jkimlab/DESCHRAMBLER#14]
Hi,kind regards.
I have successfully run the example file, but I received an error when running my own data.
I think the error is the '_in ref chr7 wrong ref position_' ,maybe the problem is in the net file, but I don't know how to deal with it.
Of course, my thinking could be wrong, can you please help me?

I print it out:
## Constructing syntenic fragments ##
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr7.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr11.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr3.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr4.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr1.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr9.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr10.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr2.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr5.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr8.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr6.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr7.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr11.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr3.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr4.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr1.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr9.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr10.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr2.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr5.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr8.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr6.net
- processing spc2.raw.segs
- processing spc3.raw.segs
- getting segments from spc2.processed.segs
- getting segments from spc3.processed.segs
- adding descendent spc2
  in ref chr7 .........
  in ref chr11 ....
  in ref chr3 .........
  in ref chr4 ........
  in ref chr1 ...........
  in ref chr9 ........
  in ref chr10 ......
  in ref chr2 ..........
  in ref chr5 ...........
  in ref chr8 ........
  in ref chr6 .........
- adding outgroup spc3
  in ref chr7 wrong ref position: 49 spc1 chr7 4511181 spc3 chr5 +
make: *** [Makefile:23: Building.Blocks] Error 1
readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/create_blocklist.pl line 18.
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr7.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr11.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr3.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr4.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr1.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr9.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr10.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr2.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr5.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr8.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc2/net/chr6.net
- - processing spc2.raw.segs
- getting segments from spc2.processed.segs
- adding descendent spc2
  in ref chr7 .........
  in ref chr11 ....
  in ref chr3 .........
  in ref chr4 ........
  in ref chr1 ...........
  in ref chr9 ........
  in ref chr10 ......
  in ref chr2 ..........
  in ref chr5 ...........
  in ref chr8 ........
  in ref chr6 .........
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr7.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr11.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr3.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr4.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr1.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr9.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr10.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr2.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr5.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr8.net
- reading /public/home/HuBiLin/08.chr_align/0_result/chainNet/spc1/spc3/net/chr6.net
- processing spc3.raw.segs
- getting segments from spc3.processed.segs
- adding descendent spc3
  in ref chr7 .......
  in ref chr11 ..
  in ref chr3 .......
  in ref chr4 ......
  in ref chr1 .........
  in ref chr9 ......
  in ref chr10 .....
  in ref chr2 .......
  in ref chr5 .....
  in ref chr8 ......
  in ref chr6 .....
TREE ((spc2,spc1)@,spc3);

readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/wrap_recon_apcf.pl line 37.
Use of uninitialized value $tmp in scalar chomp at /public/home/HuBiLin/software/DESCHRAMBLER/script/wrap_recon_apcf.pl line 39.
Use of uninitialized value $tmp in substr at /public/home/HuBiLin/software/DESCHRAMBLER/script/wrap_recon_apcf.pl line 40.
substr outside of string at /public/home/HuBiLin/software/DESCHRAMBLER/script/wrap_recon_apcf.pl line 40.
Use of uninitialized value $numblocks in concatenation (.) or string at /public/home/HuBiLin/software/DESCHRAMBLER/script/wrap_recon_apcf.pl line 41.
Use of uninitialized value $bdist_f in concatenation (.) or string at /public/home/HuBiLin/software/DESCHRAMBLER/script/estparJC.pl line 14.
spc1 /public/home/HuBiLin/08.chr_align/0_result/tree.txt APCFs.500K/SFs/bpdist.txt 
Use of uninitialized value $bdist_f in string at /public/home/HuBiLin/software/DESCHRAMBLER/script/estparJC.pl line 17.
readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/estparJC.pl line 18.
Estimate JC parameter: 0.0001
cp: cannot stat 'APCFs.500K/SFs/Genomes.Order': No such file or directory
readLeafGenomes: spc2
Couldn't open Genomes.Order , No such file or directory
readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/refine_adjprob.pl line 11.
Minimum weight = 0.0001
Conservation score file = APCFs.500K/SFs/block_consscores.txt
readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/split_weak_joins.pl line 130.
readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/split_weak_joins.pl line 130.
readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/split_weak_joins.pl line 130.
readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/join_splits.pl line 60.
readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/join_splits.pl line 131.
readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/join_splits.pl line 131.
readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/join_splits.pl line 131.
readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/join_splits.pl line 156.
readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/sort_apcfs.pl line 13.
readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/ext_join_info.pl line 114.
readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/ext_join_info.pl line 114.
readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/ext_join_info.pl line 114.
Cannot open APCFs.500K/SFs/Conserved.Segments.
readline() on closed filehandle F at /public/home/HuBiLin/software/DESCHRAMBLER/script/create_mapfile.pl line 42.

**Comment by jkimlab** [comment]
In most cases, such errors occur when there are some problems in the generated chain and net files or the used resolution value is not appropriate for your data set. 

You can try one or both of the followings.

- Recreate chain and net files
- Use different resolution value (smaller or larger) in the parameter file. The name of the parameter is RESOLUTION.

**Comment by Bilinhu** [comment]
Ok, thanks a lot. I have a try.

**Comment by Bilinhu** [comment]
Thanks a lot. I found that my chain file does not correspond to the net file, and I recreated the files to sovled the question
