### ISSUE TITLE
per-chromosome chain file with two species

### ISSUE THREAD

**Issue by DustinSokolowski** [jkimlab/DESCHRAMBLER#15]
Hey!

I have assembled a _de novo_ rodent genome and I'm looking to compute genome-wide syntenic blocks to the mm10. With only a two species tree, do I need to have the chain and net file split by each chromosome for both my genome and _mm10_, or does just my genome suffice?

Best,
Dustin

**Comment by jkimlab** [comment]
Hi Dustin,

If you just want to build synteny blocks, I recommend one of the following tools.

GMASS: https://github.com/jkimlab/GMASS

mySyntenyPortal: https://github.com/jkimlab/mySyntenyPortal

In those tools, you don’t need to worry about chain/net files. You just need to provide assembly sequence files.

Thanks.

**Comment by DustinSokolowski** [comment]
Hey,

Thank you for the quick response, and I'm sorry about my unfamiliarity with your excellent software, I think I'm going to be changing that very soon.

What I'm looking to do is take about 100 candidate tandem duplication regions (100Kb-1Mb) in my genome and visualize the synteny between species with a linear synteny view. The original plan was to use the output of DESCHRAMBLER with `syntenyPlotteR` to generate these plots in a high-throughput manner. 

![image](https://github.com/jkimlab/DESCHRAMBLER/assets/56414662/e6a9af31-be48-4f6a-9682-3a37e583a81e)

If I were to use `GMASS`, would the `CSB/` directory contain the analogous output files to look at these syntenic plots in a high throughput manner?

**Comment by jkimlab** [comment]
I don’t know about syntenyPlotteR, so I don’t know it can work with GMASS. 

But if you use mySyntenyPortal, you can create a similar webpage as shown below.

http://bioinfo.konkuk.ac.kr/synteny_portal/htdocs/synteny_browser.php?whole_spc=hg38_mm39&chr=chr1&resolution=150000

**Comment by DustinSokolowski** [comment]
Hey,

These look beautiful, though I didn't know mySyntenyPortal functioned with a custom reference based on the paper. Is there new documentation that allows for this? My assembly is currently on rapid-ensembl and not yet UCSC, so I'm not sure if it's compatible.

Best!
Dustin

**Comment by jkimlab** [comment]
mySyntenyPortal works with any assembly files. Just prepare two fasta files for each of the assemblies you want to compare, and specify their paths in the parameter file of mySyntenyPortal. Please check the Github page.

**Comment by DustinSokolowski** [comment]
Great, I see this now. Thanks so much!

Dustin
