### ISSUE TITLE
Possiblitiy of working Progressive Cactus allignments with DESCHRAMBLER

### ISSUE THREAD

**Issue by Alchimic007** [jkimlab/DESCHRAMBLER#17]
Hello,

Just wanted to ask whether it is possible to use Progressive Cactus (https://github.com/ComparativeGenomicsToolkit/cactus) alignments which are in .hal format (https://cglgenomics.ucsc.edu/data/cactus/) with DESCHRAMBLER, and if it is possible then is there some algorithm for that. 

Thank you.

**Comment by jkimlab** [comment]
Sorry, the format is not supported.

**Comment by Alchimic007** [comment]
Thank you
