### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by gepmat** [jkimlab/DESCHRAMBLER#2]
Make seems to work, but I get this error while running the main script:
"Compilation failed in require at /usr/share/perl/5.22/base.pm line 97."

It seems to be the main issue here, could you help me with this ? 

Thanks,

Matthieu

**Comment by gepmat** [comment]
> Make seems to work, but I get this error while running the main script:
> "Compilation failed in require at /usr/share/perl/5.22/base.pm line 97."
> 
> It seems to be the main issue here, could you help me with this ?
> 
> Thanks,
> 
> Matthieu

**Comment by jkimlab** [comment]
Dear Matthieu,

I don’t know the exact reason, but it may be related with Perl libraries in your computer (conflict with the ones included in DESCHRAMBLER?).
I recommend using other machines if you have.

Best,

Jaebum

**Comment by gepmat** [comment]
dear Jaebum,

what are all the dependencies used in DESHCRAMBLER ?
we tested the software on a virtual machine and it still not works whereas no conflict should have been possible there..
run your program should be a huge help for our project and I hope it will work with your help.

regards,

Matthieu

________________________________
De : jkimlab <notifications@github.com>
Envoyé : vendredi 12 juillet 2019 07:42
À : jkimlab/DESCHRAMBLER
Cc : gepmat; State change
Objet : Re: [jkimlab/DESCHRAMBLER] Compilation failed (#2)

Dear Matthieu,

I don’t know the exact reason, but it may be related with Perl libraries in your computer (conflict with the ones included in DESCHRAMBLER?).
I recommend using other machines if you have.

Best,

Jaebum

**Comment by jkimlab** [comment]
Thanks a lot for using our program.

All Perl modules required for DESCHRAMBLER are in the "lib/perl” directory. If it is because of Perl module conflict, I think you can install all modules in the “lib/perl” directories in your server, and remove the line starting with “use lib …” in all Perl script files in the “script” directory.

Thanks,
Jaebum
