### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by Alchimic007** [jkimlab/DESCHRAMBLER#20]
Hello,
I'm really sorry for bothering you again. I've got an error while trying to run my first experiment with DESCHRAMBLER. I'm running it on virtual machine (Ubuntu 18.04). Here is my tree ((Homo_sapiens:0.00644,Bos_taurus:0.0041)@:0.5689,Choloepus_hoffmanni:0.005); Here is my directory structure /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/chain/chr1.chain ... chr22 and  /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr1.net and same for  Choloepus_hoffmanni directory. Chains and nets were created  from cactus hal file https://cgl.gi.ucsc.edu/data/cactus/241-mammalian-2020v2.hal using UCSC (maftopsl, axtChain, chainNet) and HALtools toolkit (hal2maf) apps. When I'm running DESCHRAMBLER it goes like this:  maksym@maksym-virtualBox:~$ perl /home/maksym/Downloads/DESCHRAMBLER/DESCHRAMBLER.pl /home/maksym/Downloads/Deschrambler_test/params.txt 

## Constructing syntenic fragments ##

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr8.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr18.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr22.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr9.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr12.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr17.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr11.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr21.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr5.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr16.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr10.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr6.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr20.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr7.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr2.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr3.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr4.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr15.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr13.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr14.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr19.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr1.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr8.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr18.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr22.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr9.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr12.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr17.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr11.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr21.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr5.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr16.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr10.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr6.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr20.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr7.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr2.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr3.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr4.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr15.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr13.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr14.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr19.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr1.net

- processing Bos_taurus.raw.segs

- processing Choloepus_hoffmanni.raw.segs

- getting segments from Bos_taurus.processed.segs

- getting segments from Choloepus_hoffmanni.processed.segs

- adding descendent Bos_taurus

  in ref chr8 ....

  in ref chr18 .

  in ref chr22 ...

  in ref chr9 ....

  in ref chr12 ....

  in ref chr17 .....

  in ref chr11 .....

  in ref chr21 .

  in ref chr5 ....

  in ref chr16 ...

  in ref chr10 .....

  in ref chr6 ..

  in ref chr20 .

  in ref chr7 ........

  in ref chr2 ......

  in ref chr3 .....

  in ref chr4 ....

  in ref chr15 .....

  in ref chr13 .

  in ref chr14 ...

  in ref chr19 .....

  in ref chr1 .......

- adding outgroup Choloepus_hoffmanni

  in ref chr8 ..............................

  in ref chr18 ................

  in ref chr22 ......

  in ref chr9 ......................

  in ref chr12 ..........................

  in ref chr17 ..............

  in ref chr11 .........................

  in ref chr21 ......

  in ref chr5 ......................................

  in ref chr16 ...............

  in ref chr10 ............................

  in ref chr6 ..................................

  in ref chr20 ............

  in ref chr7 ...............................

  in ref chr2 ..................................................

  in ref chr3 ..........................................

  in ref chr4 .......................................

  in ref chr15 ................

  in ref chr13 ....................

  in ref chr14 ...................

  in ref chr19 .......

  in ref chr1 ...............................................

Segmentation fault (core dumped)

make: *** [Makefile:57: Genomes.Order] Error 139

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr8.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr18.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr22.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr9.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr12.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr17.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr11.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr21.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr5.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr16.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr10.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr6.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr20.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr7.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr2.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr3.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr4.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr15.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr13.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr14.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr19.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/net/chr1.net

- processing Bos_taurus.raw.segs

- getting segments from Bos_taurus.processed.segs

- adding descendent Bos_taurus

  in ref chr8 ....

  in ref chr18 .

  in ref chr22 ...

  in ref chr9 ....

  in ref chr12 ....

  in ref chr17 .....

  in ref chr11 .....

  in ref chr21 .

  in ref chr5 ....

  in ref chr16 ...

  in ref chr10 .....

  in ref chr6 ..

  in ref chr20 .

  in ref chr7 ........

  in ref chr2 ......

  in ref chr3 .....

  in ref chr4 ....

  in ref chr15 .....

  in ref chr13 .

  in ref chr14 ...

  in ref chr19 .....

  in ref chr1 .......

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr8.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr18.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr22.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr9.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr12.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr17.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr11.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr21.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr5.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr16.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr10.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr6.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr20.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr7.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr2.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr3.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr4.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr15.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr13.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr14.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr19.net

- reading /home/maksym/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Choloepus_hoffmanni/net/chr1.net

- processing Choloepus_hoffmanni.raw.segs

- getting segments from Choloepus_hoffmanni.processed.segs

- adding descendent Choloepus_hoffmanni

  in ref chr8 ..............................

  in ref chr18 ................

  in ref chr22 ......

  in ref chr9 ......................

  in ref chr12 ..........................

  in ref chr17 ..............

  in ref chr11 .........................

  in ref chr21 ......

  in ref chr5 ......................................

  in ref chr16 ...............

  in ref chr10 ............................

  in ref chr6 ..................................

  in ref chr20 ............

  in ref chr7 ...............................

  in ref chr2 ..................................................

  in ref chr3 ..........................................

  in ref chr4 .......................................

  in ref chr15 ................

  in ref chr13 ....................

  in ref chr14 ...................

  in ref chr19 .......

  in ref chr1 ...............................................

TREE ((Homo_sapiens:0.00644,Bos_taurus:0.0041)@:0.5689,Choloepus_hoffmanni:0.005);

0 Homo_sapiens /home/maksym/Downloads/Deschrambler_test/tree.txt /home/maksym/Downloads/Deschrambler_test/APCFs.300/SFs/bpdist.txt

Illegal division by zero at /home/maksym/Downloads/DESCHRAMBLER/script/estparJC.pl line 41, <GEN0> line 1.

Estimate JC parameter: 

inferAdjProb - inferring the posterior probability of block adjacency

  usage: inferAdjProb refspc parameter-alpha tree-file genome-file

readline() on closed filehandle F at /home/maksym/Downloads/DESCHRAMBLER/script/refine_adjprob.pl line 11.

Minimum weight = 0.0001

Conservation score file = /home/maksym/Downloads/Deschrambler_test/APCFs.300/SFs/block_consscores.txt

- Totally 0 APCFs

Segmentation fault (core dumped)

maksym@maksym-virtualBox:~$

**Comment by Alchimic007** [comment]
I also give you my chain and net example to check. If you will have some time please look at them, may be problem is in my inputs
[chr1.chain.txt](https://github.com/jkimlab/DESCHRAMBLER/files/13416712/chr1.chain.txt)
[chr1.net.txt](https://github.com/jkimlab/DESCHRAMBLER/files/13416730/chr1.net.txt)
I'm sending txt version of examples of my chains and nets (bos_taurus in here), because github does not allow originals. Maybe this will help to understand what is a problem, because I do not get a clue what is wrong. Thank you and sorry for bothering

**Comment by Alchimic007** [comment]
I have also re-run examples, they works fine

**Comment by jkimlab** [comment]
Please search the closed issues in Github first. 
There were some issues related to the segmentation fault.

**Comment by Alchimic007** [comment]
I have checked all issues concerning segmentation fault error, namely #1, 7, 13, 18, and it seems they are not applying to my case fully, because in my case files are extracted from hal file and not generated from fasta files. As for naming of files as mentioned in issue #7, my files were named that way as they are from the start: maksym@maksym-virtualBox:~/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/chain$ ls

chr10.chain  chr12.chain  chr14.chain  chr16.chain  chr18.chain  chr1.chain   chr21.chain  chr2.chain  chr4.chain  chr6.chain  chr8.chain

chr11.chain  chr13.chain  chr15.chain  chr17.chain  chr19.chain  chr20.chain  chr22.chain  chr3.chain  chr5.chain  chr7.chain  chr9.chain

maksym@maksym-virtualBox:~/Downloads/Deschrambler_test/chainNet/Homo_sapiens/Bos_taurus/chain$ 

**I just want to understand wheter I need to regenerate chains and nets or the problem is in parameters here is my parameter and config files**: params file# Reference species
REFSPC=Homo_sapiens

# Output directory
OUTPUTDIR=/home/maksym/Downloads/Deschrambler_test/APCFs.300
#OUTPUTDIR=/home/maksym/Downloads/Deschrambler_test/Out_RACA.anctest

# Block resolution (bp)
RESOLUTION=300000

# Newick tree file
# Refer to the sample file 'tree.txt'.
TREEFILE=/home/maksym/Downloads/Deschrambler_test/tree.txt

# Minimum adjacency scores
MINADJSCR=0.0001

# Config and make files for syntenic fragment construction
# Refer to the sample files 'config.SFs' and 'Makefile.SFs'.
# You need to change settings in the sample configuration file (config.SFs) according to your data
# You don't need to change anything in the Makefile.SFs.
CONFIGSFSFILE=/home/maksym/Downloads/Deschrambler_test/config.SFs
MAKESFSFILE=/home/maksym/Downloads/Deschrambler_test/Makefile.SFs    

****config file:# path of a net files 
>netdir
/home/maksym/Downloads/Deschrambler_test/chainNet

# path of a chain files 
>chaindir
/home/maksym/Downloads/Deschrambler_test/chainNet

# species-name tag1 tag2
# tag1 (0: ref-species, 1: descendents, 2: outgroup)
# tag2 (1: chromosome assembly, 0: others)
# Warning for tag2: Use the value 1 only when a chromosome name starts with "chr". 
>species
Homo_sapiens 0 1
Bos_taurus 1 0
Choloepus_hoffmanni 2 0

# block resolution (bp): DO NOT CHANGE
>resolution
<resolutionwillbechanged>
   I will be vey appreciated for any help. Thank you

**Comment by jkimlab** [comment]
I think it may be caused by the incompatibility of the used cactus alignments. I recommend using the lastz alignments for making chain/net files.
