### ISSUE TITLE
Totally 0 APCFs

### ISSUE THREAD

**Issue by aaannaw** [jkimlab/DESCHRAMBLER#21]
Hello, Professor
Recently I used `DESCHRAMBLER` to reconstruct the ancestral chromosome fragments for  two species （`Ma and Mp`) from the same genus with the outgroup of a species of related genus (`Efon`).  Taking `Ma `as reference, we built the `pair alignment `between Ma and Mp, Efon using `lastz and lastal pipeline` respectively. When I ran DESCHRAMBLER taking the `chain` and` net` files from `lastal pipeline`, I got the error:
 

> 0 Ma /data/01/user158/kuangzhuoran/wanna/Last2AncKary/2023.12/10.DESCHRAMBLER/tree.txt /data/01/user158/kuangzhuoran/wanna/Last2AncKary/2023.12/10.DESCHRAMBLER/result/SFs/bpdist.txt
>  Illegal division by zero at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/estparJC.pl line 41, <GEN0> line 1.
> Estimate JC parameter: 
> inferAdjProb - inferring the posterior probability of block adjacency
>   usage: inferAdjProb refspc parameter-alpha tree-file genome-file
> readline() on closed filehandle F at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/refine_adjprob.pl line 11.
> Minimum weight = 0.0001
> Conservation score file = /data/01/user158/kuangzhuoran/wanna/Last2AncKary/2023.12/10.DESCHRAMBLER/result/SFs/block_consscores.txt
> Totally 0 APCFs
> sh: line 1: 3279879 Segmentation fault      (core dumped) /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../code/makeBlocks/createCarFile /data/01/user158/kuangzhuoran/wanna/Last2AncKary/2023.12/10.DESCHRAMBLER/result/SFs/config.file /data/01/user158/kuangzhuoran/wanna/Last2AncKary/2023.12/10.DESCHRAMBLER/result/Ancestor.APCF /data/01/user158/kuangzhuoran/wanna/Last2AncKary/2023.12/10.DESCHRAMBLER/result/SFs/Conserved.Segments > /data/01/user158/kuangzhuoran/wanna/Last2AncKary/2023.12/10.DESCHRAMBLER/result/APCFs

Then I input the `chain` and `net` files from `lastz pipeline` to run DESCHRAMBLER, I got too much blocks as follows:  
![image](https://github.com/jkimlab/DESCHRAMBLER/assets/109299053/2a624fae-063c-4074-9c12-aef73f8c3654)
Moreover, professor Marco Corbo suggested a more recent version  allowed for the the use of multiple reference genomes to strengthen the analysis. Could you give me any suggestions. Looking forward with your reply.
Best wishes!
Na wan

**Comment by jkimlab** [comment]
Hi Na wan,

I am not sure but the synteny blocks were not constructed correctly. 
Can you share the SFs.log file in the output directory and the parameter file?

**Comment by aaannaw** [comment]
Hello, professor
I am sorry for late response. I will show you these files based on the nets and chains from lastz and lastal respectively:
`files from analysis based on lastz :`
```
params.txt:
# Reference species
REFSPC=Ma

# Output directory
OUTPUTDIR=APCFs.300K
#OUTPUTDIR=Out_RACA.anctest

# Block resolution (bp)
RESOLUTION=300000

# Newick tree file
# Refer to the sample file 'tree.txt'.

TREEFILE=tree.txt

# Minimum adjacency scores
MINADJSCR=0.0001

# Config and make files for syntenic fragment construction
# Refer to the sample files 'config.SFs' and 'Makefile.SFs'.
# You need to change settings in the sample configuration file (config.SFs) according to your data
# You don't need to change anything in the Makefile.SFs.
CONFIGSFSFILE=config.SFs
MAKESFSFILE=Makefile.SFs
```
```
config.SFs
# path of a net files 
>netdir
/data/01/user158/kuangzhuoran/wanna/Last2AncKary/chainNet

# path of a chain files 
>chaindir
/data/01/user158/kuangzhuoran/wanna/Last2AncKary/chainNet

# species-name tag1 tag2
# tag1 (0: ref-species, 1: descendents, 2: outgroup)
# tag2 (1: chromosome assembly, 0: others)
# Warning for tag2: Use the value 1 only when a chromosome name starts with "chr". 
>species
Ma 0 0
Mp 1 0
Efon 2 0 

# block resolution (bp): DO NOT CHANGE
>resolution
<resolutionwillbechanged>
```
```
Tree.txt：
 (Efon:0.01009,(Mp:0.00552,Ma:0.00585)@:0.00647);
```
Files from analysis based on lastal:
```
config.SFs
# path of a net files 
>netdir
/data/01/user158/kuangzhuoran/wanna/Last2AncKary/2023.12/10.DESCHRAMBLER/chainNet

# path of a chain files 
>chaindir
/data/01/user158/kuangzhuoran/wanna/Last2AncKary/2023.12/10.DESCHRAMBLER/chainNet

# species-name tag1 tag2
# tag1 (0: ref-species, 1: descendents, 2: outgroup)
# tag2 (1: chromosome assembly, 0: others)
# Warning for tag2: Use the value 1 only when a chromosome name starts with "chr". 
>species
Ma 0 0
Mp 1 0 
Efon 2 0 

# block resolution (bp): DO NOT CHANGE
>resolution
<resolutionwillbechanged>
```
```
params.txt
# Reference species
REFSPC=Ma

# Output directory
OUTPUTDIR=result
#OUTPUTDIR=Out_RACA.anctest

# Block resolution (bp)
RESOLUTION=300000

# Newick tree file
# Refer to the sample file 'tree.txt'.
TREEFILE=tree.txt

# Minimum adjacency scores
MINADJSCR=0.0001

# Config and make files for syntenic fragment construction
# Refer to the sample files 'config.SFs' and 'Makefile.SFs'.
# You need to change settings in the sample configuration file (config.SFs) according to your data
# You don't need to change anything in the Makefile.SFs.
CONFIGSFSFILE=config.SFs
MAKESFSFILE=Makefile.SFs
```
```
tree.txt:
(Efon:0.01009,(Mp:0.00552,Ma:0.00585)@:0.00647);
```
The log files will be added with upload files.
[lastal.run.log](https://github.com/jkimlab/DESCHRAMBLER/files/13630512/lastal.run.log)
[lastz.run.log](https://github.com/jkimlab/DESCHRAMBLER/files/13630513/lastz.run.log)

**Comment by jkimlab** [comment]
I also need the SFs.log file in the output directory.

**Comment by aaannaw** [comment]
Sorry， Professor, I  can not find the  SFs.log  fille in the output directory.  I also run  the example file provided and I can likely not find SFs.log file. Maybe it has other naming? 
![image](https://github.com/jkimlab/DESCHRAMBLER/assets/109299053/1ef80a91-c0af-4914-9f80-5bb40a480d0f)
![image](https://github.com/jkimlab/DESCHRAMBLER/assets/109299053/1a966ec2-80f5-448c-9964-6307a3e6de49)
![image](https://github.com/jkimlab/DESCHRAMBLER/assets/109299053/e8fb57c6-0e43-44da-a0ef-9596a8df84a7)

**Comment by jkimlab** [comment]
OK.
Did you see any error messages when you ran the example data? If not, it may be caused by an incorrect value of the resolution parameter. 

Your assemblies are scaffolds, not chromosome-level sequences. In that case, the default 300Kbp resolution may be too large especially if your assemblies are highly fragmented.

Decrease the resolution, say 50Kbp or smaller, and try again.

**Comment by YingChen94** [comment]
Hello Professor, I am getting the same error (below) when running the example dataset. I decrease the resolution to 50Kbp and it still showed the same error. I couldn't find the SFs.log file either.  Do you have any insights where the issue comes from? 

```
0 spc1 /home/ying_local/DESCHRAMBLER/examples/tree.txt /home/ying_local/DESCHRAMBLER/examples/APCFs.300K/SFs/bpdist.txt
Illegal division by zero at /home/ying_local/DESCHRAMBLER/script/estparJC.pl line 41, <GEN0> line 1.
Estimate JC parameter: 
inferAdjProb - inferring the posterior probability of block adjacency
  usage: inferAdjProb refspc parameter-alpha tree-file genome-file

readline() on closed filehandle F at /home/ying_local/DESCHRAMBLER/script/refine_adjprob.pl line 11.
Minimum weight = 0.0001
Conservation score file = /home/ying_local/DESCHRAMBLER/examples/APCFs.300K/SFs/block_consscores.txt
- Totally 0 APCFs
Segmentation fault (core dumped)
```

**Comment by jkimlab** [comment]
The example dataset must work without decreasing the resolution. I am not sure but the program may not be compiled correctly in your machine.
If you can provide additional log output, I can take a look at it.

**Comment by davidlougheed** [comment]
Hi @jkimlab 
I'm working with @YingChen94 on this. I'm using the `bioperl-update` branch since otherwise I would need to downgrade Perl a bunch of versions. 

Here is the compilation log from `make`: [make.log](https://github.com/user-attachments/files/16110101/make.log)

**Comment by YingChen94** [comment]
Hello @jkimlab, somehow the program ran successfully after @davidlougheed recompile to get the log today (i.e. ran `make clean` and then `make` again to get the logs). I am not sure what exactly got changed but perhaps the `Makefile.SFs`? Anyway thank you for your help!

**Comment by jkimlab** [comment]
No problem. Good to hear that!

**Comment by jenny315** [comment]
Hello,@aaannaw,
The figure below your drawing is very good. Could you please tell me how to draw it？

> 教授您好 最近我曾为`DESCHRAMBLER`两个物种（ ）重建祖先染色体片段，`Ma and Mp`它们来自同一属，而该属的外群属于相关属（`Efon`）。我们以此为参考，分别使用 Ma 和 Mp、Efon`Ma `构建了。当我运行 DESCHRAMBLER 并从 中提取和文件时，我得到了错误：`pair alignment ``lastz and lastal pipeline``chain`` net``lastal pipeline`
> 
> > 0 Ma /data/01/user158/kuangzhuoran/wanna/Last2AncKary/2023.12/10.DESCHRAMBLER/tree.txt /data/01/user158/kuangzhuoran/wanna/Last2AncKary/2023.12/10.DESCHRAMBLER/result/SFs/bpdist.txt
> > 非法除以零 at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/estparJC.pl 第 41 行，第 1 行。
> > 估计 JC 参数：
> > inferAdjProb - 推断块邻接的后验概率
> > 用法：inferAdjProb refspc 参数 alpha 树文件 基因组文件
> > readline() on closed filehandle F at /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/refine_adjprob.pl 第 11 行。
> > 最小权重 = 0.0001
> > 守恒分数文件 = /data/01/user158/kuangzhuoran/wanna/Last2AncKary/2023.12/10.DESCHRAMBLER/result/SFs/block_consscores.txt
> > 总共 0 个 APCF 
> > sh：第 1 行：3279879 分段错误（核心转储） /data/01/user158/kuangzhuoran/software/DESCHRAMBLER/script/../code/makeBlocks/createCarFile /data/01/user158/kuangzhuoran/wanna/Last2AncKary/2023.12/10.DESCHRAMBLER/result/SFs/config.file /data/01/user158/kuangzhuoran/wanna/Last2AncKary/2023.12/10.DESCHRAMBLER/result/Ancestor.APCF /data/01/user158/kuangzhuoran/wanna/Last2AncKary/2023.12/10.DESCHRAMBLER/result/SFs/Conserved.Segments > /data/01/user158/kuangzhuoran/wanna/Last2AncKary/2023.12/10.DESCHRAMBLER/result/APCFs
> 
> 然后我输入`chain`和`net`文件来`lastz pipeline`运行DESCHRAMBLER，我得到了太多的块，如下所示： 此外，Marco Corbo教授建议使用更新的版本，允许使用多个参考基因组来加强分析。你能给我任何建议吗？期待您的回复。 祝一切顺利！ Na wan ![图像](https://private-user-images.githubusercontent.com/109299053/288029608-2a624fae-063c-4074-9c12-aef73f8c3654.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NzU2ODIsIm5iZiI6MTcyMDk3NTM4MiwicGF0aCI6Ii8xMDkyOTkwNTMvMjg4MDI5NjA4LTJhNjI0ZmFlLTA2M2MtNDA3NC05YzEyLWFlZjczZjhjMzY1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQxNjQzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDUzNmYwNzg1NWI2N2Q2YjMyNmY3ZmRkZGQxZWI1YzVkZTE0ZWQyNzgzNGM5ZjIwMmUzZGI1YzVkYTY3ZjQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nrPIfYVsp-cmzs0FfJvhKd-QeKcB8NwA2WzKMEChlcs)
