### ISSUE TITLE
the using of the software

### ISSUE THREAD

**Issue by wwenc** [jkimlab/DESCHRAMBLER#22]
I can't get the right answer by using the data of example, some important files contain nothing. Please give me a hand.
![Uploading 截图 2024-02-28 23-04-45.png…]()

**Comment by jkimlab** [comment]
Your uploaded file is not visible. Please upload it again.

**Comment by wwenc** [comment]
![截图 2024-02-28 23-04-45](https://github.com/jkimlab/DESCHRAMBLER/assets/152481196/699c1f3d-951f-4a19-8095-61aa57a9ccb7)

**Comment by wwenc** [comment]
![截图 2024-02-29 10-20-31](https://github.com/jkimlab/DESCHRAMBLER/assets/152481196/efda6fd5-c046-4d85-b5df-a68da5a7e730)

**Comment by wwenc** [comment]
![截图 2024-02-29 10-21-04](https://github.com/jkimlab/DESCHRAMBLER/assets/152481196/f7a207ed-43fb-4e9b-af30-b3d987d38037)

**Comment by jkimlab** [comment]
Sorry but we need all output from right after running the program.

**Comment by wwenc** [comment]
There are all my output after running the programe. 
[APCF.log](https://github.com/jkimlab/DESCHRAMBLER/files/14444554/APCF.log)
[APCFs.300K.zip](https://github.com/jkimlab/DESCHRAMBLER/files/14444570/APCFs.300K.zip)

**Comment by jkimlab** [comment]
Thanks. Here is one of your error messages.

Error - Could not open net dir /public/home/WuWenchao/DESCHRAMBLER-master/examples/chainNet/spc1/spc2/net

I think the chain/net files are not in a proper directory. Please check if the file and directory paths are all correct.

If you are not sure, please delete and reinstall our program. And then try again.

**Comment by wwenc** [comment]
I reinstall the software, but the problem still exists.

**Comment by jkimlab** [comment]
I don’t know what happened in your server. Please check if the files are in the path shown in the error message. On Feb 29, 2024, at 5:12 PM, wwenc ***@***.***> wrote:﻿
I reinstall the software, but the problem still exits.

**Comment by wwenc** [comment]
Something seens wrong, and I can't figure it out
[log.txt](https://github.com/jkimlab/DESCHRAMBLER/files/14445277/log.txt)
[APCFs.300K.zip](https://github.com/jkimlab/DESCHRAMBLER/files/14445281/APCFs.300K.zip)

**Comment by jkimlab** [comment]
After reinstalling the program, the previous problem was fixed. For the new problem, you can find the solution in the issue #12.

**Comment by jkimlab** [comment]
Or alternatively, you can download new code from a new branch named "bioperl-update" using the following command and try again.

git clone -b bioperl-update https://github.com/jkimlab/DESCHRAMBLER.git

I just created the new branch.

**Comment by wwenc** [comment]
Thank you very much, this problem is solved.
