### ISSUE TITLE
question about varied results

### ISSUE THREAD

**Issue by jenny315** [jkimlab/DESCHRAMBLER#26]
Hello, Professor，

I have some questions about the result. Could you please give some stuggestion for me

- My results are summarised below，
when Block resolution is 50k, the result I got (form file APCF_size.txt) 609 APCFs  total 228079891 bp.
when Block resolution is 100K,  the result I got (form file APCF_size.txt) 135 APCFs total 140661249 bp.
when Block resolution is 300k, the result I got  (form file APCF_size.txt) 56  APCFs total 64342708 bp.

- My questions are summarised below,
1. I'm getting varied results with different resolutions, the amount and total length of APCFs are quite inconsistent. Is this normal? Maybe these results aren't usable at all.
2. I know there can't be so many ancestral chromosomes (even up to 600). Therefore, I'm not sure which results to use.
3. Even the biggest result obtained here (609 APCFs, comprising 228079891 bp) is still quite small (in comparison to the genome size of the species used). Is this normal? Or would you suggest me to adjust the parameters further?

- The genome size and chromosome number of the selected species are as follows, respectively：
```
name	sum_leh	chr_num
Ly	668,967,811	24
Cs 	445,139,357	22
Dr	1,345,101,833	25
Gg	1,100,911,310	40
Lo	891,144,077	29
Lp	625,267,304	24
Ol	734,040,372	24
Tr	281,572,362	22
```
- Species relationships and ancestor node settings```@``` marker are detailed in the files "config.SFs" and "tree.txt"

- - config.SFs
```
# path of a net files
>netdir
/data/jenny/61MD5jenny/deschr/02spec/chainNet

# path of a chain files
>chaindir
/data/jenny/61MD5jenny/deschr/02spec/chainNet

# species-name tag1 tag2
# tag1 (0: ref-species, 1: descendents, 2: outgroup)
# tag2 (1: chromosome assembly, 0: others)
# Warning for tag2: Use the value 1 only when a chromosome name starts with "chr".
>species
Ly 0 1
Cs 1 1
Dr 1 1
Gg 2 1
Lo 1 1
Lp 1 1
Ol 1 1
Tr 1 1

# bLok resolution (bp): DO NOT CHANGE
>resolution
<resolutionwillbechanged>
```
- - tree.txt
```
(((((((Ly:0.00582,Lp:0.01924):0.05216,Tr:0.12628):0.01846,Cs:0.13082):0.01913,Ol:0.12087):0.10993,Dr:0.1699):0.08193,Lo:0.13718)@:0.103875,Gg:0.120100);
```
Many thanks, I appreciate your prompt response.
Jenny

**Comment by jkimlab** [comment]
The total length depends on the total length of constructed synteny blocks (common genomic blocks among all ingroup species). Because the size of the smallest genome in your case is 281Mbp (Tr), and so you cannot obtain synteny blocks with a total length exceeding 281Mbp with any smaller resolution.

In addition, if the genomes of your ingroup species are highly rearranged, it is difficult to concatenate the synteny blocks, which results in the generation of many APCFs.

**Comment by jenny315** [comment]
Hello, Professor, Thanks very much for your response.

- After deleting the smallest genome species, "TR", I still get similar results. When Block resolution is 50k, the result I got (form file APCF_size.txt)  622 APCFs total of 242508911 bp.
- - As we know from earlier studies, all of these species—aside from "LO"—experienced a WGD (Whole Genome Duplication) in comparison to the hypothesized ancestor(marker "@"), the node where this event took place is indicated by a "!" marker below. Did this incident affect the program's running results?
```
((((((Ly:0.00582,Lp:0.01924):0.07107,Cs:0.13082):0.01913,Ol:0.12087):0.10993,Dr:0.1699):!0.08193,Lo:0.13718)@:0.103875,Gg:0.120100);
```
Many thanks, I appreciate your prompt response.
Jenny

**Comment by jkimlab** [comment]
That means the amount of common genomic regions among the remaining species is about 242Mbp. If you want to increase the amount, you need to find and remove more genomes of species that can’t be aligned well against your reference.

**Comment by jenny315** [comment]
Ok, thanks, I will explore further.
