### ISSUE TITLE
Can a TimeTree-Derived Phylogenetic Tree Be Used as Software Input?

### ISSUE THREAD

**Issue by wwenc** [jkimlab/DESCHRAMBLER#27]
Hello, Professor,

I would like to ask whether a phylogenetic tree constructed using TimeTree can be used as an input file for the software. In this case, the branch lengths represent divergence times. Could you please provide some guidance on this?

Thank you in advance for your help!
[log.txt](https://github.com/user-attachments/files/17964372/log.txt)

**Comment by jkimlab** [comment]
Yes, you can.
But your problem is the incorrect setting of a reference species. Is it PSTE? PSTE must be in the tree.

**Comment by wwenc** [comment]
thank you for your help
