### ISSUE TITLE
out of order

### ISSUE THREAD

**Issue by lskfs** [jkimlab/DESCHRAMBLER#4]
partitionGenomes run into "out of order" and then the program stop.

I have tried range of resolutions (10K, 50K, 100K, 200K, 300K) to solve this but none works. 

Then I filtered the chain file to drop out alignment with length less 50K and got the same error.

Could you kindly explain how this happened? if there is any solution?

**Comment by jkimlab** [comment]
I think it is a problem in the chain/net files. 
How did you make the chain/net files? Please regenerate the chain/net files and try again.

Thanks.
