### ISSUE TITLE
DESCHRAMBLER usage problem

### ISSUE THREAD

**Issue by JhinAir** [jkimlab/DESCHRAMBLER#5]
Hi,
Currently, I am using DESCHRAMBLER to reconstruct the ancestral genome for Mammal / Reptile / Amniote nodes. It works well for the  Reptile / Amniote reconstructions, but not for mammal. All the inputs are the same except for the "@" location in the tree file. My tree file is bellowing with Mustache_toad as outgroup:
(((((Rattlesnake:0.1548,Common_lizard:0.0709):0.0849,Tuatara:0.0752):0.0178,((Emu:0.0890,Alligator:0.0693):0.0112,Sea_turtle:0.0575):0.0126)@1:0.0375,(((((Camel:0.0407,Whale:0.0367):0.0210,Human:0.0474):0.0111,Asian_elephant:0.0586):0.0825,Kangaroo:0.1219):0.0290,Platypus:0.1479)@2:0.0531)@3:0.2121,Mustache_toad:0.2121);
"@" was only placed on one location for each run. For the "**@1**" (Reptile) and "**@3**" (Amniote), it works fine. But for "**@2**" (Mammal), it always outputs errors as bellowing:
#############################################################################
1253 Emu ./DESCHRAMBLER/02Run_Mammal/tree.R4.txt ./out_300Kb_Mammal/SFs/bpdist.txt
Estimate JC parameter: 0.000463660350578281
readLeafGenomes: Camel
readLeafGenomes: Whale
readLeafGenomes: Human
readLeafGenomes: Asian_elephant
readLeafGenomes: Kangaroo
readLeafGenomes: Platypus
T=0
Initializing Camel (ingroup)
readline() on closed filehandle F at ./DESCHRAMBLER-master/script/refine_adjprob.pl line 11.
Minimum weight = 0.0001
Conservation score file = ./out_300Kb_Mammal/SFs/block_consscores.txt
Totally 1253 APCFs
############################################################################# 
The possible reason I guess maybe for "@1" and "@3" runs, the basic tree structure is ((spe1,spe2)@,spe3), but for "@2" run, it is  ((((spe1,spe2),spe3),spe4)@,spe5). Could it be such a reason?  If so, how to fix it? Otherwise could you please help to find the possible problems?

Another question is that the output results seem to be unstable if you increase/decrease the number of either ingroup or outgroup (even only one). Could you please help give some advice to trim the output APCF?

Best,
Jing

**Comment by jkimlab** [comment]
Dear Jing,

Thanks a lot for using DESCHRAMBLER.

For your first issue, what is a reference? I guess the reference is under the common ancestor "@1". That may be the reason of the errors. The current version was only tested with target ancestors that contains the reference as one of descendants. 

For your second issue, it depends on the assembly quality of used species. To produce reliable output, high-quality genome assemblies need to be used.

Best,

Jaebum

**Comment by JhinAir** [comment]
Dear Jaebum,

Yes, "Emu" is the reference. That means if I want to reconstruct the mammal ancestral genome, I need to use one of them as ref, right? As the construction of the alignment is time-consuming, I'd like to ask if there is a way to use "Conserved.Segments" as input, only keeping the CSs with the new ref species (such as human). Do you think it's appropriate?

Best,
Jing

**Comment by jkimlab** [comment]
Yes, you are right. 
And your suggestion should be fine in terms of methods. But current version was not tested in such setting. 
Please try to run and see what you can get. 

Best,

Jaebum

**Comment by JhinAir** [comment]
Thanks a lot for the help! I'd try.
Best,
Jing
