### ISSUE TITLE
species selection

### ISSUE THREAD

**Issue by xuyuannnn** [jkimlab/DESCHRAMBLER#8]
Hi , I have a question. could you tell me that can't the reference species and outgroup be the same species ？thanks!

**Comment by jkimlab** [comment]
Hi,

Outgroup species are defined as the species outside of the sub-tree defined by reference and other ingroup species. So using the same species for the reference and outgroup is the same as using only reference and ingroup species.

Hope I correctly understood your question.

Thanks.

**Comment by YingChen94** [comment]
Do you have any suggestions in choosing reference species? For ingroup species, is it better to use chromosome-level assemblies only, or shall I use as many species as possible including scaffold-level ones? Thanks!

**Comment by jkimlab** [comment]
A reference genome is used as a backbone for constructing synteny blocks. So it is better if its assembly is more contiguous and accurate, and I recommend using the most contiguous and accurate one as the reference. 

In addition, the synteny blocks are built by using alignable genomic regions against the genomes of ingroup species. So if you want to increase the coverage of the reference genome in a target ancestor, it is better to use chromosome-level assemblies if they are available.

**Comment by YingChen94** [comment]
This makes sense. Thank you Professor Kim!
